Silence gcc 9 warnings & fix potential unaligned access
Silences:

    src/blockchain_db/lmdb/db_lmdb.cpp: In member function ‘virtual void cryptonote::BlockchainLMDB::open(const string&, cryptonote::network_type, int)’:
    src/blockchain_db/lmdb/db_lmdb.cpp:1473:63: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
     1473 |     if (db_version > static_cast<decltype(db_version)>(VERSION))
          |                                                               ^
    src/blockchain_db/lmdb/db_lmdb.cpp:1480:68: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
     1480 |     else if (db_version < static_cast<decltype(db_version)>(VERSION))
          |                                                                    ^

which happens because the `decltype()` here is const, and gcc apparently
now apparently warns on a cast to a const cast result.

While here I also noticed and fixed what looks like an unaligned access
that could be a potential problem on non-x86 architectures.