Fix GCC5.5 not being smart about evaluating dead branches
src/quorumnet/bt_serialize.h: In instantiation of 'void quorumnet::detail::bt_deserialize<T, typename std::enable_if<std::is_integral<_Tp>::value, void>::type>::operator()(std::istream&, T&) [with T = long unsigned int; typename std::enable_if<std::is_integral<_Tp>::value, void>::type = void; std::istream = std::basic_istream<char>]':
src/quorumnet/bt_serialize.cpp:107:17:   required from here
src/quorumnet/bt_serialize.h:161:75: error: logical 'or' of collectively exhaustive tests is always true [-Werror=logical-op]
if (sizeof(T) < sizeof(int64_t) && (read.first.i64 < smin || read.first.i64 > smax))